Vagrant.configure("2") do |config|
config.vm.define :pxe_client do |pxe_client|

    pxe_client.vm.box = 'debian/buster64'
    pxe_client.vm.network "private_network", type: "dhcp"
    pxe_client.vm.provider :virtualbox do |vb|
      vb.memory = '1024'
      vb.cpus = '1'
      vb.gui = 'true'
    end
  end
end
