#!/bin/bash

local users = ["daniel", "clemens", "felix", "andreas", "mario", "philipp", "johannes" ]

#bash loop über users

for u in users
DO
  echo "Welcome $u in k3s"
  useradd $u && passwd $u
DONE
