---
- name: Converge
  hosts: all
  vars: 
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_listen_ipv6:
      - any
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: true
    bind_query_log: 'data/query.log'
    bind_check_names: 'master ignore'
    bind_zone_master_server_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    bind_zone_minimum_ttl: "2D"
    bind_zone_ttl: "2W"
    bind_zone_time_to_refresh: "2D"
    bind_zone_time_to_retry: "2H"
    bind_zone_time_to_expire: "2W"
    bind_zone_domains:
      - name: 'k3s'
        networks:
          - '10.0.0'
        hostmaster_email: "office@gepardec.com"
        hosts:
          - name: verify
            ip: 10.0.0.1
  pre_tasks:
    - debug:
        msg: "{{ hostvars }}"
  roles:
    - role: bertvv.bind
