---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include dhcp"
      include_role:
        name: "dhcp"
  vars:
    dhcp_global_default_lease_time: 28800   # 8hrs
    dhcp_global_max_lease_time: 43200       # 12 hrs
    dhcp_global_subnet_mask: 255.255.255.0
    dhcp_global_broadcast_address: 10.0.2.255
    # dhcp_global_routers: 10.0.2.2
    dhcp_global_domain_name: example.com
    dhcp_global_domain_name_servers:
      - 8.8.8.8
      - 9.9.9.9
    dhcp_global_bootp: ignore
    dhcp_global_booting: ignore
    dhcp_global_next_server: 10.0.2.20
    dhcp_global_filename: boot.img

    dhcp_global_classes:
      - name: vbox
        match: 'match if binary-to-ascii(16,8,":",substring(hardware, 1, 3)) = "8:0:27"'

    dhcp_subnets:
      - ip: 10.0.2.0
        netmask: 255.255.255.0
        domain_name_servers:
          - 10.0.2.10
        range_begin: 10.0.2.60
        range_end: 10.0.2.250

    dhcp_hosts:
      - name: dns
        mac: '00:de:ad:be:ef:00'
        ip: 10.0.2.10
      - name: pxe
        mac: '00:de:ad:be:ef:01'
        ip: 10.0.2.20
      - name: ntp
        mac: '00:de:ad:be:ef:02'
        ip: 10.0.2.30
      - name: bastion
        mac: '00:de:ad:be:ef:03'
        ip: 10.0.2.40
      - name: lb
        mac: '00:de:ad:be:ef:04'
        ip: 10.0.2.50

    dhcp6_enable: false
