---
# sudopassword is stored in an ansible-vault:
# ansible_sudo_pass: mysudopassword
- name: Include vars from vault
  include_vars:
    file: ../secret

- name: debug vars
  debug:
    msg: Creating "{{workingdir}}unzipped"

- name: Create a directory if it does not exist
  file:
    path: "{{workingdir}}unzipped"
    state: directory

- name: Extract image
  unarchive:
    src: "{{workingdir}}{{imagename}}"
    dest: "{{workingdir}}unzipped"

- name: Erase target drive(SD) and copy
  become: yes
  shell: dd if={{workingdir}}unzipped/{{image}} of=/dev/mmcblk0 status=progress

- name: Enable SSH via the SD
  become: yes
  file:
    path: /run/media/work/rootfs/boot/ssh
    state: touch
    mode: '1777'
