---

- name: Include vars from vault
  include_vars:
    file: "{{ vaultfilepath }}"

- name: Create new user and add to groups
  become: yes
  user:
    name: "{{newusername}}"
    password: "{{newpassword | password_hash('sha512')}}"
    generate_ssh_key: yes
    append: yes
    groups: pi, adm, dialout, cdrom, sudo, audio, video, plugdev, games, users, input, netdev, spi, i2c, gpio