= Role Name

This role is for bootstrapping a raspberry pi 4.

== Principle of Operation
- Download Image
- Unpack Image
- Write Image to SD (dd will erase the target drive, double check {{ sdcardpath }})
- Write ssh file to bootpath to enable ssh on the rpi
- Configure static IP 192.168.0.10

You can now connect your machine via ethernet and ssh into the Raspberry Pi.
For bonuspoints use another Role and setup the Pi via ssh.

== Specifics
If this does not run on your machine it might be due to:

- device name of the sdcard differs
- mount point names differ
- uses udiskctl for automatic mounting
- uses dd to copy the image to sd
- uses whoami to get the username for some of the paths used

== Requirements

- a `password.yml` that contains the password for the ansible vault called secret.
- an ansible vault called `secret` containing the become(sudo) password. +
__ansible-vault create secret__

== Role Variables

You need to set the ANSIBLE_VAULT_PASSWORD_FILE in the molecule/default/molecule.yml.
Point to a file containing the ansible-vault password.
All the other config is in vars/main.yml.

== Example Usage

ansible-playbook playbook-bootstrapsdcard.yml --vault-password-file roles/bootstrapsdcard/password.yml
