# vi: ft=ruby

require 'rbconfig'

ROLE_NAME = 'dhcp'
VAGRANTFILE_API_VERSION = '2'

distros = [
  { name: 'centos', box: 'centos/8' },
  { name: 'debian', box: 'debian/buster64' }
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  distros.each do |distro|
    srv_name = 'srv' + distro[:name]
    config.vm.define srv_name do |node|
      node.vm.hostname = srv_name
      node.vm.box = distro[:box]

      node.vm.network :private_network,
        ip: '192.168.0.1'

      node.vm.provision 'ansible' do |ansible|
        ansible.compatibility_mode = '2.0'
        ansible.playbook = 'playbook.yml'
      end
    end
  end
end