---
- name: Create BIOS Directory
  file:
    path: "{{projectroot}}bios"
    state: directory
    mode: '0777'

- name: Copy libraries for BIOS 1/2
  copy:
    src: "/usr/lib/syslinux/modules/bios/{{ item }}"
    dest: "{{projectroot}}bios/{{ item }}"
    mode: '777'
    remote_src: yes
  with_items:
      - ldlinux.c32
      - vesamenu.c32
      - libcom32.c32
      - libutil.c32

- name: Copy libraries for BIOS 2/2
  copy:
    src: "/usr/lib/PXELINUX/pxelinux.0"
    dest: "{{projectroot}}bios/pxelinux.0"
    mode: '777'
    remote_src: yes

- name: Create EFI Directory
  file:
    path: "{{projectroot}}efi64"
    state: directory
    mode: '0777'

- name: Copy libraries for EFI 1/3
  copy:
    src: "/usr/lib/syslinux/modules/efi64/{{item}}"
    dest: "{{projectroot}}efi64/{{item}}"
    mode: '777'
    remote_src: yes
  with_items:
      - vesamenu.c32
      - libcom32.c32
      - libutil.c32

- name: Copy libraries for EFI 2/3
  copy:
    src: "/usr/lib/syslinux/modules/efi64/ldlinux.e64"
    dest: "{{projectroot}}efi64/ldlinux.e64"
    mode: '777'
    remote_src: yes

- name: Copy libraries for EFI 3/3
  copy:
    src: "/usr/lib/SYSLINUX.EFI/efi64/syslinux.efi"
    dest: "{{projectroot}}efi64/syslinux.efi"
    mode: '777'
    remote_src: yes

- name: Create Bootfile Directory
  become: yes
  file:
    path: /mnt/data/netboot/pxelinux.cfg
    state: directory
    mode: '0777'

- name: Create Default Bootfile
  become: yes
  copy:
    src: files/default
    dest: /mnt/data/netboot/pxelinux.cfg/default
    mode: '777'
