---
# tasks file for setuppxeserver
- name: Get the username for vars/main.yml
  become: false
  local_action: command whoami
  register: username

- name: Install prerequisites
  import_tasks: ../tasks/prerequisites.yml

- name: Setup directories
  import_tasks: ../tasks/directories.yml

- name: Copy files from image
  import_tasks: ../tasks/copyimage.yml

- name: Create the default PXE bootfile
  import_tasks: ../tasks/createbootfile.yml