---
# tasks file for pxe-boot

- name: include basic-setup tasks
  include_tasks: basic_setup.yml
  tags:
    - always

- name: include tftp-setup tasks
  include_tasks: tftp_setup.yml
  tags:
    - always

- name: include pxe-setup tasks
  include_tasks: pxe_setup.yml
  tags:
    - always

...