---

- name: Copy content of boot folder to tftp root directory
  command: "cp -r /boot/* {{ tftp_root_directory }}/"

- name: Export filesystems
  command: {{ item }}
  become: true
  with_items:
    - "echo '/nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)' | sudo tee -a /etc/exports"
    - "echo '{{ tftp_root_directory }} *(rw,sync,no_subtree_check,no_root_squash)' | sudo tee -a /etc/exports"

- name: configre rpcbind service
  service:
    name: rpcbind
    enabled: true
    state: restarted

- name: configure nfs-kernel-server service
  service:
    name: nfs-kernel-server
    enabled: true
    state: restarted

- name: replace client fstab
  template:
    src: client.cmdline.txt
    dest: "{{ tftp_root_directory}}/cmdline.txt"

- name: replace client fstab
  template:
    src: client.fstab
    dest: /nfs/client1/etc/fstab


...