---

- name: Copy content of boot folder to tftp root directory
  copy:
    src: /boot/
    dest: "{{ tftp_root_directory }}"
    remote_src: true

- name: Export filesystems
  command: "echo '/nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)' | sudo tee -a /etc/exports"

- name: Export tftp-root directory filesystem
  command: "echo '{{ tftp_root_directory }} *(rw,sync,no_subtree_check,no_root_squash)' | sudo tee -a /etc/exports"

- name: configure rpcbind service
  service:
    name: rpcbind
    enabled: true
    state: restarted

- name: configure nfs-kernel-server service
  service:
    name: nfs-kernel-server
    enabled: true
    state: restarted
  async: 60
  poll: 5

- name: replace client fstab
  template:
    src: client.cmdline.txt
    dest: "{{ tftp_root_directory}}/cmdline.txt"

- name: replace client fstab
  template:
    src: client.fstab
    dest: /nfs/client1/etc/fstab
  become: true

...