#@IgnoreInspection BashAddShebang
# -*- mode: ruby -*-
# vi: set ft=ruby :

#########################
$CPU = 1
$MEMORY = 1024
$CPUEXECUTIONCAP = 50 # does not work with hyper-v
$IP = "192.169.0.10"   # does not work with hyper-v # https://www.vagrantup.com/docs/hyperv/limitations.html
$BASEOS = "gvfoster/raspbian"
$SSH=2210
#########################

Vagrant.configure("2") do |config|
  config.vm.box = $BASEOS

  config.vm.provider "virtualbox" do |v|
    v.memory = $MEMORY
    v.cpus = $CPU
    v.customize ["modifyvm", :id, "--cpuexecutioncap", $CPUEXECUTIONCAP]
  end

  config.vm.provider "hyperv" do |v|
    v.memory = $MEMORY
    v.cpus = $CPU
  end 

  config.vm.provider "libvirt" do |v|
    v.memory = $MEMORY
    v.cpus = $CPU
  end

  config.vm.network "private_network", ip: $IP
  config.vm.network "forwarded_port", guest: 22, host: $SSH, id: 'ssh'

  config.vm.synced_folder "../", "/vagrant"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "/vagrant/pxe-boot/playbook_vagrant.yml"
  end

end
