---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: debian/buster64
    cpus: 2
    provision: yes
provisioner:
  name: ansible
verifier:
  name: ansible
